/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#00dbe9',
        'primary': '#dbfcff',
        'inverse-surface': '#e5e1e5',
        'surface-dim': '#131316',
        'surface': '#131316',
        'surface-container-lowest': '#0e0e11',
        'inverse-on-surface': '#313033',
        'secondary': '#fface8',
        'on-background': '#e5e1e5',
        'tertiary-fixed-dim': '#d1bcff',
        'outline': '#849495',
        'surface-bright': '#39393c',
        'on-primary-fixed-variant': '#004f54',
        'on-primary-container': '#006970',
        'primary-fixed-dim': '#00dbe9',
        'error-container': '#93000a',
        'on-tertiary': '#3c0090',
        'on-tertiary-fixed-variant': '#5700c9',
        'primary-fixed': '#7df4ff',
        'on-secondary-fixed-variant': '#840076',
        'on-primary': '#00363a',
        'tertiary-fixed': '#e9ddff',
        'tertiary-container': '#e1d2ff',
        'primary-container': '#00f0ff',
        'error': '#ffb4ab',
        'inverse-primary': '#006970',
        'surface-container': '#201f22',
        'secondary-fixed-dim': '#fface8',
        'on-secondary-fixed': '#3a0033',
        'on-error-container': '#ffdad6',
        'outline-variant': '#3b494b',
        'on-surface': '#e5e1e5',
        'background': '#131316',
        'on-tertiary-container': '#7213ff',
        'surface-container-high': '#2a2a2d',
        'secondary-fixed': '#ffd7f0',
        'on-error': '#690005',
        'on-primary-fixed': '#002022',
        'surface-container-highest': '#353438',
        'on-tertiary-fixed': '#23005b',
        'on-secondary-container': '#520049',
        'surface-variant': '#353438',
        'secondary-container': '#ff24e4',
        'tertiary': '#faf3ff',
        'surface-container-low': '#1c1b1e',
        'on-surface-variant': '#b9cacb'
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px'
      },
      spacing: {
        'unit': '8px',
        'container-max': '1280px',
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px'
      },
      fontFamily: {
        'display': ['"Bodoni Moda"', 'serif'],
        'body': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg': ['"Bodoni Moda"', 'serif'],
        'display-lg-mobile': ['"Bodoni Moda"', 'serif'],
        'headline-lg': ['"Bodoni Moda"', 'serif'],
        'headline-md': ['"Bodoni Moda"', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif']
      }
    },
  },
  plugins: [],
}
